-- Esquema para AlbinaNuevo en PostgreSQL (Supabase)

-- 1. Usuarios / Roles (Extiende la autenticación de Supabase)
CREATE TABLE usuarios (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    username TEXT UNIQUE,
    nombre TEXT NOT NULL,
    rol TEXT NOT NULL CHECK (rol IN ('admin', 'empleada')),
    activo BOOLEAN DEFAULT true
);

-- 2. Categorías
CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE
);

-- 3. Proveedores
CREATE TABLE proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    telefono TEXT,
    direccion TEXT,
    activo BOOLEAN DEFAULT true
);

-- 4. Productos
CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_barras TEXT UNIQUE,
    codigo_fabrica TEXT,
    nombre TEXT NOT NULL,
    costo_lista NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    flete NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    costo_final NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    utilidad_porcentaje NUMERIC(5,2) NOT NULL DEFAULT 0.0,
    precio_contado NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    precio_tarjeta NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    stock_actual NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    stock_minimo NUMERIC(10,2) NOT NULL DEFAULT 5.0,
    stock_maximo NUMERIC(10,2) NOT NULL DEFAULT 100.0,
    unidades_bulto INTEGER DEFAULT 1,
    ubicacion TEXT,
    talle TEXT,
    observaciones TEXT,
    creado_por UUID REFERENCES usuarios(id),
    modificado_por UUID REFERENCES usuarios(id),
    categoria_id BIGINT REFERENCES categorias(id),
    proveedor_id BIGINT REFERENCES proveedores(id),
    activo BOOLEAN DEFAULT true
);

-- 5. Clientes
CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    cuit TEXT,
    domicilio TEXT,
    localidad TEXT,
    provincia TEXT,
    condicion_iva TEXT DEFAULT 'Consumidor Final',
    telefono TEXT,
    condicion_pago TEXT DEFAULT 'Contado',
    descuento_porcentaje NUMERIC(5,2) DEFAULT 0.0,
    activo BOOLEAN DEFAULT true
);

-- Insertar Consumidor Final por defecto
INSERT INTO clientes (id, nombre, cuit, condicion_iva, activo) 
VALUES (1, 'CONSUMIDOR FINAL', '00000000000', 'Consumidor Final', true);

-- 6. Caja Sesiones
CREATE TABLE caja_sesiones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_apertura TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    fecha_cierre TIMESTAMP WITH TIME ZONE,
    monto_inicial NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    monto_cierre NUMERIC(10,2),
    usuario_id UUID REFERENCES usuarios(id),
    estado TEXT DEFAULT 'ABIERTA'
);

-- 7. Caja Movimientos
CREATE TABLE caja_movimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caja_sesion_id BIGINT NOT NULL REFERENCES caja_sesiones(id),
    tipo TEXT NOT NULL,
    monto NUMERIC(10,2) NOT NULL,
    metodo_pago TEXT NOT NULL,
    descripcion TEXT,
    usuario_id UUID REFERENCES usuarios(id),
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Ventas
CREATE TABLE ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes(id),
    caja_sesion_id BIGINT NOT NULL REFERENCES caja_sesiones(id),
    usuario_id UUID REFERENCES usuarios(id),
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    subtotal NUMERIC(10,2) NOT NULL,
    descuento_total NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    total NUMERIC(10,2) NOT NULL,
    metodo_pago TEXT NOT NULL,
    tipo_comprobante TEXT DEFAULT 'TICKET',
    estado_afip TEXT DEFAULT 'PENDIENTE',
    nro_comprobante_afip TEXT,
    estado TEXT DEFAULT 'COMPLETADA'
);

-- 9. Promociones
CREATE TABLE promociones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_barras TEXT UNIQUE,
    nombre TEXT NOT NULL,
    precio_fijo NUMERIC(10,2) NOT NULL,
    activa BOOLEAN DEFAULT true
);

-- 10. Ventas Detalle
CREATE TABLE ventas_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT NOT NULL REFERENCES ventas(id),
    producto_id BIGINT REFERENCES productos(id),
    promocion_id BIGINT REFERENCES promociones(id),
    cantidad NUMERIC(10,2) NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL,
    costo_unitario NUMERIC(10,2) NOT NULL DEFAULT 0.0,
    subtotal NUMERIC(10,2) NOT NULL
);

-- 11. Promocion Detalles
CREATE TABLE promocion_detalles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promocion_id BIGINT NOT NULL REFERENCES promociones(id),
    producto_id BIGINT NOT NULL REFERENCES productos(id),
    cantidad_requerida INTEGER NOT NULL
);

-- 12. Cta Cte Movimientos
CREATE TABLE cta_cte_movimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes(id),
    caja_sesion_id BIGINT REFERENCES caja_sesiones(id),
    venta_id BIGINT REFERENCES ventas(id),
    usuario_id UUID REFERENCES usuarios(id),
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    tipo TEXT NOT NULL,
    monto NUMERIC(10,2) NOT NULL,
    detalle TEXT
);

-- 13. Cta Cte Proveedores
CREATE TABLE cta_cte_proveedores_movimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id BIGINT NOT NULL REFERENCES proveedores(id),
    caja_sesion_id BIGINT REFERENCES caja_sesiones(id),
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    tipo TEXT NOT NULL,
    monto NUMERIC(10,2) NOT NULL,
    detalle TEXT
);

-- SEGURIDAD (Row Level Security - RLS)
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE ventas ENABLE ROW LEVEL SECURITY;

-- Políticas de seguridad para bloquear a empleadas

-- (Por defecto permitiremos leer todo a todos los autenticados para no trabar el sistema de UI local)
CREATE POLICY "Lectura libre para usuarios logueados" ON productos FOR SELECT TO authenticated USING (true);
CREATE POLICY "Lectura libre para usuarios logueados" ON ventas FOR SELECT TO authenticated USING (true);

-- Solo la admin puede borrar o alterar productos
CREATE POLICY "Solo admin edita/borra productos" ON productos FOR ALL TO authenticated 
USING (
    (SELECT rol FROM usuarios WHERE id = auth.uid()) = 'admin'
);

-- Empleadas pueden crear ventas, pero no borrarlas
CREATE POLICY "Todos pueden crear ventas" ON ventas FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Solo admin edita ventas" ON ventas FOR UPDATE TO authenticated 
USING (
    (SELECT rol FROM usuarios WHERE id = auth.uid()) = 'admin'
);
CREATE POLICY "Solo admin borra ventas" ON ventas FOR DELETE TO authenticated 
USING (
    (SELECT rol FROM usuarios WHERE id = auth.uid()) = 'admin'
);
